name: brick_breaker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flame: ^1.18.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/brick_ball.png"
  
flutter:
  uses-material-design: true

